
name: CI
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps
      - name: Run tests
        run: pytest -m "e2e" -q
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results
      - name: AI suggestions
        if: always()
        run: |
          python tools/analyze_run.py --input reports/allure-results --out ai_suggestions.md || true
      - name: Upload AI suggestions
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-suggestions
          path: ai_suggestions.md
